#include "map.h"

map_t easy_map = {
	{
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, FIELD_OUTSIDE,    FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE,   
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, FIELD_EMPTY,	   FIELD_EMPTY,   		  FIELD_EMPTY,   		 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_PLAYER,  FIELD_BOX, 	   FIELD_EMPTY, 		  FIELD_EMPTY,  		 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, FIELD_EMPTY, 	   FIELD_BOX, 			  FIELD_BOX_DESTINATION, FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_OUTSIDE, FIELD_OUTSIDE,    FIELD_BOX, 			  FIELD_EMPTY, 			 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY, 		  FIELD_OUTSIDE, FIELD_EMPTY, 	   FIELD_BOX_DESTINATION, FIELD_EMPTY, 			 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX, 			  FIELD_EMPTY,   FIELD_BOX_PLACED, FIELD_BOX, 			  FIELD_BOX, 			 FIELD_BOX_DESTINATION, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY, 		  FIELD_EMPTY,   FIELD_EMPTY, 	   FIELD_BOX_DESTINATION, FIELD_EMPTY, 			 FIELD_EMPTY, 			FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE
	}
};

map_t normal_map = {
	{
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 	   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY,   FIELD_EMPTY,	 FIELD_EMPTY,	FIELD_EMPTY,   FIELD_EMPTY,   FIELD_PLAYER,  FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 	   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY,   FIELD_BOX, 	 FIELD_OUTSIDE, FIELD_BOX, 	   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 	   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY,   FIELD_BOX, 	 FIELD_EMPTY,   FIELD_EMPTY,   FIELD_BOX, 	  FIELD_OUTSIDE, FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 	   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX, 	 FIELD_EMPTY, 	FIELD_BOX, 	   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 	   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY,   FIELD_BOX, 	 FIELD_EMPTY, 	FIELD_OUTSIDE, FIELD_EMPTY,	  FIELD_OUTSIDE, FIELD_OUTSIDE,
		FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,	 FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY,   FIELD_BOX, 	 FIELD_EMPTY, 	FIELD_EMPTY,   FIELD_BOX, 	  FIELD_EMPTY,	 FIELD_EMPTY,
		FIELD_OUTSIDE, FIELD_OUTSIDE, 		  FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY, 	 FIELD_EMPTY,	FIELD_EMPTY,   FIELD_BOX,	  FIELD_EMPTY,	 FIELD_EMPTY, 	FIELD_BOX,	   FIELD_EMPTY,   FIELD_EMPTY, 	 FIELD_EMPTY,
		FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,	 FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE
	}
};

map_t hard_map = {
	{
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_EMPTY, FIELD_EMPTY, 	 FIELD_EMPTY,   FIELD_EMPTY,   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_EMPTY, FIELD_BOX,   	 FIELD_EMPTY,   FIELD_EMPTY,   FIELD_BOX, 	  FIELD_EMPTY, 	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_BOX,   FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY, 	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,   FIELD_EMPTY, 	 FIELD_EMPTY, FIELD_PLAYER,	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY, 	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX_DESTINATION, FIELD_BOX_DESTINATION, FIELD_EMPTY,   FIELD_EMPTY,   FIELD_OUTSIDE, FIELD_EMPTY, FIELD_OUTSIDE, FIELD_EMPTY,	FIELD_EMPTY,   FIELD_BOX, 	  FIELD_EMPTY, 	 FIELD_OUTSIDE,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		 FIELD_OUTSIDE, 		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_EMPTY, FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_BOX,	   FIELD_EMPTY,	  FIELD_BOX,   	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		 FIELD_OUTSIDE,  		FIELD_EMPTY,   FIELD_BOX, 	  FIELD_EMPTY,   FIELD_EMPTY, FIELD_BOX,	 FIELD_EMPTY,	FIELD_BOX,	   FIELD_EMPTY,	  FIELD_BOX,   	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE, 
		FIELD_OUTSIDE, FIELD_OUTSIDE, FIELD_OUTSIDE, 		 FIELD_OUTSIDE,  		FIELD_EMPTY,   FIELD_EMPTY,	  FIELD_EMPTY,   FIELD_EMPTY, FIELD_OUTSIDE, FIELD_EMPTY, 	FIELD_EMPTY,   FIELD_EMPTY,   FIELD_EMPTY, 	 FIELD_EMPTY,	FIELD_OUTSIDE, FIELD_OUTSIDE
	}
};
